// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYfHf94JZYGKY6s2-pgMF15PtYWEvcfbk',
    appId: '1:331496385192:android:f5096ee7e8075377a5309d',
    messagingSenderId: '331496385192',
    projectId: 'meeting-45b97',
    storageBucket: 'meeting-45b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMM0m-NdXf1YNS5UPgrHWhqh251lWjtsY',
    appId: '1:331496385192:ios:8b45afb6fec145cfa5309d',
    messagingSenderId: '331496385192',
    projectId: 'meeting-45b97',
    storageBucket: 'meeting-45b97.appspot.com',
    androidClientId: '331496385192-0kpe1s0dmjvohdc63vehd2rkl3p6tclo.apps.googleusercontent.com',
    iosClientId: '331496385192-n48j59hogaqh9feo3de1n7nq6373c44s.apps.googleusercontent.com',
    iosBundleId: 'com.example.moimbox',
  );
}
